# This CI pipeline is triggered by a Pull Request strategy, meaning that this CI pipeline can be executed whenever needed during the PR
# by adding the comment '/gcbrun' 


# The value of the - name parameter (container image or cloud builders) can be obtained from
# https://cloud.google.com/build/docs/cloud-builders
steps:

    # Prepare to test the build of the docker image
  - id: 'copy_uv_files'
    name: 'ubuntu'
    entrypoint: 'sh'
    args:
      - '-c' # Execute the following commands in a sequential manner
      - | # Allow to write commands in more than 1 row
        cp pyproject.toml uv.lock ${_DOCKERFILE_LOCATION}/.


  - id: 'validate_docker_build'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - build 
      - '-t'
      - '${_ARTREG_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTREG_NAME}/${_AGENTUI_IMAGNAME}:temp'
      - '-f'
      - '${_DOCKERFILE_LOCATION}/${_DOCKERFILE_NAME}'
      - '.'



substitutions:
  _ARTREG_NAME: ai-agents
  _ARTREG_REGION: northamerica-south1
  _AGENTUI_IMAGNAME: agent_ui
  _DOCKERFILE_LOCATION: app/frontend
  _DOCKERFILE_NAME: agent_ui.dockerfile


logsBucket: 'gs://ai_agent_assistant/build_logs'


options:
  dynamicSubstitutions: true
  logging: GCS_ONLY

