# The value of the - name parameter (container image or cloud builders) can be obtained from
# https://cloud.google.com/build/docs/cloud-builders
steps:

# As for the tests to succeed requires info from GCP, specially from secret manager
# The service account that will execute this pipeline must have permission to access secrets (Secret Manager Secret Accesor)
  - id: 'install_and_test'
    name: 'python:${_PYTHON_VERSION}'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        pip install uv==${_UV_VERSION}
        uv sync --all-groups
        cd tests
        uv run pytest


    # Prepare to test the build of the docker image
  - id: 'copy_uv_files'
    name: 'ubuntu'
    entrypoint: 'sh'
    args:
      - '-c' # Execute the following commands in a sequential manner
      - | # Allow to write commands in more than 1 row
        cp pyproject.toml uv.lock app/backend/.


  - id: 'build_agent_api_image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - build 
      - '-t'
      - '${_ARTREG_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTREG_NAME}/${_AGENTAPI_IMAGNAME}:${SHORT_SHA}'
      - '-t'
      - '${_ARTREG_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTREG_NAME}/${_AGENTAPI_IMAGNAME}:latest'
      - '-f'
      - 'app/backend/agent_api.dockerfile'
      - '.'


  - id: 'push_agent_api_image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - push 
      - '${_ARTREG_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTREG_NAME}/${_AGENTAPI_IMAGNAME}'
      - '--all-tags'



substitutions:
  _PYTHON_VERSION: "3.11"
  _UV_VERSION: "0.5.4"
  _ARTREG_NAME: ai-agents
  _ARTREG_REGION: northamerica-south1
  _AGENTAPI_IMAGNAME: agent_api


logsBucket: 'gs://ai_agent_assistant/build_logs'


options:
  dynamicSubstitutions: true
  logging: GCS_ONLY

